### ISSUE TITLE
Fails at line 5

### ISSUE THREAD

**Issue by OKNoah** [DroidsOnRoids/bitrise-step-vpnc-connect#1]
Fails here: https://github.com/DroidsOnRoids/bitrise-step-vpnc-connect/blob/master/step.sh#L5

No such file or directory.

Currently writing a script to try make the file

```zsh
#!/usr/bin/env bash
if [ ! -d /etc/vpnc ]; then
  mkdir /etc/vpnc && \
  touch /etc/vpnc/default.conf && \
  chmod g+x /etc/vpnc && \
  chmod -R g+r /etc/vpnc;
fi
```

But this requires sudo, which I haven't looked into doing yet.

**Comment by koral--** [comment]
According to https://packages.ubuntu.com/xenial/amd64/vpnc/filelist
file `/etc/vpnc/default.conf` should be installed with `vpnc` package, so this step expects that it exists.
`vpnc` is listed as apt dependency.

Are using this step on bitrise.io?

**Comment by koral--** [comment]
Closing due to lack of answer.
